### PR TITLE
Support org-mode links to search and entry buffers

### PR DESCRIPTION
**Pull request by groks**
Also gathers meta-data for org-capture and exports links to HTML.

See #34 for more details.

### CODE REVIEW

**Comment by skeeto** [comment]
As is, this would break [elfeed-org](https://github.com/remyhonig/elfeed-org) since it has the same name. The `provide` would clash. It's probably best to avoid the prefix "elfeed-org" since it's already been claimed by that package.

**Comment by groks** [comment]
Good point. I've renamed elfeed-org- -> elfeed-link-

**Comment by alphapapa** [comment]
Since #206 has been merged, this can be closed.

**Comment by skeeto** [comment]
Closing via #206 per @alphapapa.

**Pull request closed without merging**
