### PR TITLE
Add an elfeed-new-entry-parse-hook

### PR DESCRIPTION
**Pull request by algernon**
The hook is called when a new entry is parsed, with TYPE, XML and ENTRY arguments. This allows one to hook into the parsing itself, and extract metadata that the base parser does not.

For example, Planet aggregators are a lot more useful when the aggregated entrys original author is available too, but the basic parser does not extract that information, and as far as I see, the XML is not available later. Thus, this new hook, which allows me to extract that information.

I use the following code:

```elisp
(defun elfeed-goodies/parse-hook:author-name (type entry db-entry)
  (let* ((author-name (xml-query '(author name *) entry)))
    (setf (elfeed-meta db-entry :author) author-name)))
```

### CODE REVIEW

**Comment by algernon** [comment]
Note: there may be bugs in this PR, I'm seeing some errors, but not sure whether that's in the PR, or my custom functions, or if I botched up my running emacs. Will have a fresh look tomorrow, and report back.

**Comment by groks** [comment]
Thinking only about the specifics of entry author meta-data, I also would like to see that information, particularly when reading planet feeds (ie. http://planet.emacsen.org, http://planet.fedoraproject.org etc.)

But also, I came across the need in #128 which adds support for org-mode links.

Perhaps elfeed should:

- rename it's curent *author* to *feed-author* as that's what it is
- gather new meta-data *entry-author* (described here)
- the old *author* can now alias *entry-author* if that was published, falling back to *feed-author*

Then author information can be conveniently be shown in the UI, used in org-capture templates etc.

**Comment by algernon** [comment]
Pushed an update, there was a bug in the code: I copied a bunch of code, and didn't notice that while atom uses `entry` as a loop variable, the rss parsers use `item`. So the code threw errors on RSS feeds. The update corrects that.

Will have a go at @groks' suggestion during the day, if all goes well.

**Comment by skeeto** [comment]
Thanks! This is probably what elfeed-new-entry-hook should have been in the first place.

**Pull request closed without merging**
