### PR TITLE
Collect feeds from multiple sources for elfeed-add-feed (#181)

### PR DESCRIPTION
**Pull request by holomorph**
finally got around to it!

### CODE REVIEW

**Comment by skeeto** [comment]
Thanks! I like the way you've implemented it, especially with the `elfeed-feed-functions` customization, except that it's not applied correctly to `elfeed-add-feed`. You use the result of `elfeed-candidate-feeds` (a list) as the `DEFAULT-VALUE` argument, which the documentation says "if non-nil, should be a string." It's definitely not working correctly because of this, though it might appear to be because it gets a generic minibuffer history.

I suggest using the `hist` argument instead. Unfortunately due to the archaic interface, it requires a dynamically scoped variable. Below I declare a special variable `elfeed--add-hist`, which gets bound around the `read-from-minibuffer` call.

~~~el
(defvar elfeed--add-hist)

(defun elfeed-add-feed (url)
  "Manually add a feed to the database."
  (interactive
   (list
    (let ((elfeed--add-hist (elfeed-candidate-feeds)))
      (read-from-minibuffer "URL: " nil nil nil 'elfeed--add-hist))))
  ...)
~~~

Beyond this there is still another issue. The default is just an empty string (`""`), which the rest of the function does not handle gracefully. Perhaps instead it should use the `DEFAULT-VALUE` argument, with the prompt being dynamically created to indicate what the default value is. This should gracefully handle the case when there are no candidates.

Also, I suggest using `cl-pushnew` in `elfeed-candidate-feeds` rather than plain `push`, in case the same URL is returned by multiple sources.

~~~el
(when (not (zerop (length val)))
  (cl-pushnew val res :test #'equal))
~~~

**Comment by holomorph** [comment]
My `read-from-minibuffer` reads
```
Sixth arg DEFAULT-VALUE, if non-nil, should be a string, which is used
  as the default to `read' if READ is non-nil and the user enters
  empty input.  But if READ is nil, this function does _not_ return                        
  DEFAULT-VALUE for empty input!  Instead, it returns the empty string.

  Whatever the value of READ, DEFAULT-VALUE is made available via the
  minibuffer history commands.  DEFAULT-VALUE can also be a list of
  strings, in which case all the strings are available in the history,
  and the first string is the default to `read' if READ is non-nil.
```
I harbor much dislike for the `HIST` argument :)  Since `minibuffer-history` is already dynamic I just bound that when trying to work around this when turning on `lexical-binding` in `replace.el`.  Also, in this case I don't think `HIST` makes as much sense, since here we are trying to provide defaults which we seek with `M-n`, not history we revisit with `M-p`.  Having written this, the above docstring now appears confusing since it refers to both defaults and actual minibuffer history as "history"

Perhaps some logic indicating the default as the car of DEFAULT-VALUE in the prompt, and changing the result to said default if we get an empty string would be alright?
``` elisp
(defun elfeed-add-feed (url)
  "Manually add a feed to the database."
  (interactive
   (list
    (let* ((feeds (elfeed-candidate-feeds))
           (prompt (if feeds (concat "URL (default " (car feeds)  ": ")
                     "URL: "))
           (res (read-from-minibuffer prompt nil nil nil nil feeds)))
      (if (and (zerop (length (elfeed-cleanup res))) feeds)
          (car feeds)
        (user-error "????")))))
  ...)
```
Good call on using `cl-pushnew`, thanks.

**Comment by skeeto** [comment]
I understand now. That's what I get for not reading into the next
paragraph. I noticed M-p was a generic history and thought it wasn't
working, but I now see the correct items with M-n. What you're doing
with DEFAULT-VALUE is indeed fine.

Your change to the prompt is exactly what I was looking for, too. Except
that it needs to return res if it's not empty. And, of course, something
more informative than "????" as an error message.

Make the prompt change and the cl-pushnew change, and I'll merge it.

**Comment by holomorph** [comment]
I did a couple other things that seemed sensible to me:
- add `elfeed-looks-like-url-p` as a condition to add a URL to the list of candidates
- Move `elfeed-clipboard-get` to the end of the hook.  I figured the cases where point happened to be in EWW or on top of a URL somewhere, if someone is doing M-x elfeed-add-feed there then that is probably the link they are after.

**Comment by skeeto** [comment]
Squashed and merged as 455e58e. Thanks!

**Comment by holomorph** [comment]
Nice, thanks

**Pull request closed without merging**
