### PR TITLE
Simple Gopher support via cURL

### PR DESCRIPTION
**Pull request by jtecca**
This is my initial hacking on making elfeed support RSS feed files from the gopher protocol.  This is still in-progress, but would appreciate any review of the existing code so far before I get too deep into the other work that I need to do for this if anyone has time for a review.

I have tested a handful of my existing HTTP-based feeds to ensure that there's been no regressions, as well as my feed for my gopherhole at `gopher://tilde.institute/0/~jtecca/rss.xml` and I can see my posts show up.

Things that are still missing:
* While I've added code to the curl capabilities to check for gopher support, that support isn't being checked before making a request, so I'll need to add in a handler for that.
* Potentially some way of having a handler to specify how to open gopher:// links in a preferred browser.  I use Elpher to browse on the gophersphere, but right now I'd have to do some hacking of the internal default url-browser to open gopher links differently than http links.

I'll make sure these commits get squashed before any merging happens.

### CODE REVIEW

**Comment by la-ruby** [comment]
@jtecca personal curiosity - why folks still use gopher in 2021 ?

**Comment by jtecca** [comment]
@la-ruby for me personally, its because it represents a simpler version of the internet that I can access on resource-restrained devices.  The content in the gophersphere tends to really resonate with me as it tends to be more mindful than stuff on the web.

**Comment by jtecca** [comment]
@skeeto this is ready for at least an initital review in order to close out #408.

Unlike my prior comment, I didn't implement a per-URL cache for protocol since that would require re-checking protocol on every check of the feeds or keeping a cache around.  It was simpler to let the existing machinery specify if you had an unsupported protocol in *elfeed-log* instead.

I added a basic unit test, but am more than happy to add more coverage if you want.

**Comment by jtecca** [comment]
```elfeed/tests on  jtecca/gopher-support [+]
✦ ❯ emacs -batch -Q -L .. -L . -l elfeed-tests.el -f ert-run-tests-batch
Running 39 tests (2021-01-18 08:26:20-0800, selector ‘t’)
   passed   1/39  elfeed-autotags (0.011179 sec)
   passed   2/39  elfeed-clamp (0.000048 sec)
   passed   3/39  elfeed-cleanup (0.000057 sec)
   passed   4/39  elfeed-curl--protocol-type (0.000046 sec)
   passed   5/39  elfeed-db-dates (0.063656 sec)
   passed   6/39  elfeed-db-feed-entries (0.003339 sec)
   passed   7/39  elfeed-db-merge (0.000504 sec)
   passed   8/39  elfeed-db-meta (0.000384 sec)
   passed   9/39  elfeed-db-size (0.073102 sec)
   passed  10/39  elfeed-db-tag (0.000528 sec)
   passed  11/39  elfeed-db-visit (0.034123 sec)
   passed  12/39  elfeed-directory-empty-p (0.000377 sec)
   passed  13/39  elfeed-entries-from-x (0.015066 sec)
   passed  14/39  elfeed-feed-type (0.000973 sec)
   passed  15/39  elfeed-float-time (0.000663 sec)
   passed  16/39  elfeed-format-column (0.000057 sec)
   passed  17/39  elfeed-goto-line (0.000053 sec)
   passed  18/39  elfeed-keyword->symbol (0.000043 sec)
   passed  19/39  elfeed-kill-line (0.000053 sec)
   passed  20/39  elfeed-looks-like-url-p (0.000087 sec)
   passed  21/39  elfeed-move-to-first-empty-line (0.000058 sec)
   passed  22/39  elfeed-opml (0.009529 sec)
   passed  23/39  elfeed-parse-filter-time-durations (0.000346 sec)
   passed  24/39  elfeed-protocol-relative-url (0.013855 sec)
   passed  25/39  elfeed-readable-p (0.000083 sec)
   passed  26/39  elfeed-ref (0.020659 sec)
   passed  27/39  elfeed-ref-pack (0.086292 sec)
   passed  28/39  elfeed-resize-vector (0.000093 sec)
   passed  29/39  elfeed-search-compile-filter (0.000752 sec)
   passed  30/39  elfeed-search-unparse-filter (0.000116 sec)
   passed  31/39  elfeed-slurp-spit (0.000611 sec)
   passed  32/39  elfeed-tagger (0.000713 sec)
   passed  33/39  elfeed-time-duration (0.000181 sec)
   passed  34/39  elfeed-time-duration-absolute (0.000331 sec)
   passed  35/39  elfeed-update-location (0.000671 sec)
   passed  36/39  elfeed-valid-regexp-p (0.000094 sec)
   passed  37/39  elfeed-xml-base (0.001999 sec)
   passed  38/39  elfeed-xml-parse-region (0.101739 sec)
   passed  39/39  xml-query (0.000230 sec)

Ran 39 tests, 39 results as expected, 0 unexpected (2021-01-18 08:26:21-0800, 0.444207 sec)
```

**Comment by skeeto** [comment]
Great work! Thanks, Jeff! I made a few minor tweaks to your commit before 
merging. I also followed with a commit (af15a21) giving the capabilities 
function a more generic result rather than a specific :gopher property.

Also thanks for providing a test gopher:// feed, since I don't know where 
else I'd find one.

Let me know if you come up with a solution for opening gopher:// URLs. 
It's too bad url-browse doesn't already know how to handle that.

**Pull request closed without merging**
