### PR TITLE
Support display tags with customized icons

### PR DESCRIPTION
**Pull request by stardiviner**
Improve elfeed looking by display tags with icons.

Here is the screenshot of the effect:

image

### CODE REVIEW

**Comment by stardiviner** [comment]
@skeeto gentle ping....

**Comment by Thaodan** [comment]
Maybe move this to an external package or optional feature? I've thought of doing something like this either your way or by using faces if possible.
However some might not like it.

**Comment by stardiviner** [comment]
If you have ideas to implement similar things. It's great. Using external package for this simple feature is not a good idea. I'm currently using a local fork of elfeed. So I will wait for your implementation. Now I close this PR.

**Comment by Thaodan** [comment]
As suggested you could just make this optional or implementing
format-strings, I was thinking of something like
gnus-summary-line-format (C-h v gnus-summary-line-format RET).

I just suggest this I don't necessarily have the time to implement such a feature.

**Comment by stardiviner** [comment]
Oh, I misunderstand your meaning. I will consider to make it optional and `gnus-summary-line-format`. When I updated, will update this PR. Thanks.

**Comment by brongulus** [comment]
Hey, any updates regarding this PR, would love to see this as part of the official repo.

**Pull request closed without merging**
